name: build

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    paths-ignore:
      - "**/coverage.svg"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

permissions:
  # Setting token permissions to read-only follows the principle of least privilege. This
  # is important because attackers may use a compromised token with write access to push
  # malicious code into the project.
  # See https://github.com/ossf/scorecard/blob/e42af756609b2cde6d757fd45ea05ddf0016ff62/docs/checks.md#token-permissions
  contents: read

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v2

      - name: Fix kernel mmap rnd bits
        # Asan in llvm 14 provided in ubuntu 22.04 is incompatible with
        # high-entropy ASLR in much newer kernels that GitHub runners are
        # using leading to random crashes: https://reviews.llvm.org/D148280
        run: sudo sysctl vm.mmap_rnd_bits=28

      - name: Dependency Install
        shell: bash
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: sudo apt update; sudo apt install -y openssl libssl-dev lcov; ./prepare.sh

      - name: Build and Test
        shell: bash
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ./github_action_build.sh

      - name: Create badge
        uses: rrmcguinness/lcov_gh_badges@v1.1.2
        with:
          file: ./build/raft_cov.info.cleaned
          access_token: ${{ secrets.COVERAGE_TOKEN }}
          style: flat
          icon_name: googlecloud
          label: 'Coverage'
          label_color: 'ffffff'
          critical: 60
          critical_color: '9c2c9c'
          warning: 75
          warning_color: 'd68f0c'
          success_color: '43ad43'
          message_color: 'ffffff'
